# Phase 2: Writing & Analysis {#phase-2}

7. <!--S: Create an executable script documenting the code required to load the raw data into a tabular format, and de-identify human subjects if applicable-->Create an executable script documenting the code required to load the raw data into a tabular format, and de-identify human subjects if applicable
    + Document this preprocessing ("data wrangling") procedure in the `prepare_data.R` file.
    + This file is intended to document steps that can not or should not be replicated by end users, unless they have access to the raw data file.
    + These are steps you would run only once, the first time you load data into R.
    + Make this file as short as possible; only include steps that are absolutely necessary
8. <!--S: Save the data into a plain-text tabular format like `.csv`. When using open data, commit this file to 'Git'. When using closed data, commit a checksum of the file, and a synthetic copy of the data.-->Save the data using `open_data()` or `closed_data()`
    + <font colour = "red">__WARNING:__ Once you commit a data file to the 'Git' repository, its record will be retained forever (unless the entire repository is deleted). Assume that pushing data to a 'Git' remote repository cannot be undone. Follow the mantra: "Never commit something you do not intend to share".</font>
    + When using external data sources (e.g., obtained using an API), it is recommended to store a local copy, to make the project portable and to ensure that end users have access to the same version of the data you used.
9. <!--S: Write the manuscript using a dynamic document generation format, with code chunks to perform the analyses.-->Write the manuscript in `Manuscript.Rmd`
    + Use code chunks to perform the analyses. The first code chunk should call `load_data()`
    + Finish each sentence with one carriage return (enter); separate paragraphs with a double carriage return.
10. <!--S: Commit every small change to the 'Git' repository-->Regularly Commit your progress to the Git repository; ideally, after completing each small and clearly defined task.
    + In the top-right panel of 'RStudio', select the 'Git' tab
    + Select the checkboxes next to all files whose changes you wish to Commit
    + Click the Commit button.
    + In the pop-up window, write an informative "Commit message".
    + Click the Commit button below the message dialog
    + Click the green arrow labeled "Push" to send your commit to the remote repository
11. <!--S: Use comprehensive citation-->While writing, cite essential references with one at-symbol, `[@essentialref2020]`, and non-essential references with a double at-symbol, `[@@nonessential2020]`.
