--- 
title: "Writing A Reproducible Manuscript In R With WORCS"
author: "Caspar van Lissa, Neha Moopen, Bianca Kramer"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This book contains contains information and materials for a single-day workshop on 'Writing a Reproducible Paper in R with WORCS'." 
---

# Welcome!

Open Science is becoming increasingly popular and relevant, and a world of opportunity is opening up to make your work fully reproducible. This is not without its challenges: best practices for reproducible science include a number of tools that you may never have used or even heard of before: _Are you using version control? How are you managing your dependencies? Are you writing your manuscript as an executable document?_

For those who would like to get started with an open and reproducible workflow, without dealing with a mountain of new tools and platforms, we introduce WORCS, a _Workflow for Open Reproducible Code in Science_. The workflow is written for R, but you do not need to have prior programming experience to join this workshop. Having the motivation to step out of your comfort zone — and into a new one — is the most important prerequisite.

WORCS is an R package that takes you from data to published paper in a single streamlined workflow, making the entire process of your analysis, up to the submission of your manuscript, reproducible. The WORCS workflow optionally facilitates pre-registration, sharing your code and your data (safely!), and the submission of a pre-print.

This workshop will give you an overview of the workflow and introduce you to its use. You will create your first reproducible project by going through all steps of the workflow yourself.
